Traceback (most recent call last):
  File "/home/filippo/miniconda3/envs/sta2003/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/filippo/miniconda3/envs/sta2003/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/filippo/miniconda3/envs/sta2003/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/home/filippo/miniconda3/envs/sta2003/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/filippo/miniconda3/envs/sta2003/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/filippo/miniconda3/envs/sta2003/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/filippo/miniconda3/envs/sta2003/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
Xtr, Ytr, Xte, Yte, scaler = forecasting_datasets(ross_ts[:,None], 
                                                  horizon=5,
                                                  test_percent = 0.1)
print(f"Xtr shape: {Xtr.shape}\nYtr shape: {Ytr.shape}\nXte shape: {Xte.shape}\nYte shape: {Yte.shape}")
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[51], line 1[0m
[0;32m----> 1[0m Xtr, Ytr, Xte, Yte, scaler [38;5;241m=[39m [43mforecasting_datasets[49m(ross_ts[:,[38;5;28;01mNone[39;00m], 
[1;32m      2[0m                                                   horizon[38;5;241m=[39m[38;5;241m5[39m,
[1;32m      3[0m                                                   test_percent [38;5;241m=[39m [38;5;241m0.1[39m)
[1;32m      4[0m [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mXtr shape: [39m[38;5;132;01m{[39;00mXtr[38;5;241m.[39mshape[38;5;132;01m}[39;00m[38;5;130;01m\n[39;00m[38;5;124mYtr shape: [39m[38;5;132;01m{[39;00mYtr[38;5;241m.[39mshape[38;5;132;01m}[39;00m[38;5;130;01m\n[39;00m[38;5;124mXte shape: [39m[38;5;132;01m{[39;00mXte[38;5;241m.[39mshape[38;5;132;01m}[39;00m[38;5;130;01m\n[39;00m[38;5;124mYte shape: [39m[38;5;132;01m{[39;00mYte[38;5;241m.[39mshape[38;5;132;01m}[39;00m[38;5;124m"[39m)

[0;31mNameError[0m: name 'forecasting_datasets' is not defined

